// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgqec5DhOrv-bbvec1NMuUIvn1jRDaYig',
    appId: '1:320677223861:web:0de9506379964e1f918dfc',
    messagingSenderId: '320677223861',
    projectId: 'minimal-music-player-4243a',
    authDomain: 'minimal-music-player-4243a.firebaseapp.com',
    storageBucket: 'minimal-music-player-4243a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY7ZfKzriCkUczhy8peQ1ba2wqxFZtNnk',
    appId: '1:320677223861:android:5970db38c85b6a44918dfc',
    messagingSenderId: '320677223861',
    projectId: 'minimal-music-player-4243a',
    storageBucket: 'minimal-music-player-4243a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByMOPXceMh9ZdbYDdiTghQqpM0OTaWUVA',
    appId: '1:320677223861:ios:b5664a898135a4d1918dfc',
    messagingSenderId: '320677223861',
    projectId: 'minimal-music-player-4243a',
    storageBucket: 'minimal-music-player-4243a.firebasestorage.app',
    iosBundleId: 'com.example.minimalMusicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByMOPXceMh9ZdbYDdiTghQqpM0OTaWUVA',
    appId: '1:320677223861:ios:b5664a898135a4d1918dfc',
    messagingSenderId: '320677223861',
    projectId: 'minimal-music-player-4243a',
    storageBucket: 'minimal-music-player-4243a.firebasestorage.app',
    iosBundleId: 'com.example.minimalMusicPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgqec5DhOrv-bbvec1NMuUIvn1jRDaYig',
    appId: '1:320677223861:web:31907d812a7793ca918dfc',
    messagingSenderId: '320677223861',
    projectId: 'minimal-music-player-4243a',
    authDomain: 'minimal-music-player-4243a.firebaseapp.com',
    storageBucket: 'minimal-music-player-4243a.firebasestorage.app',
  );
}
